import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CtaBand } from "@/components/site/cta-band";
import { ArchitectureFlow, ProductVisual } from "@/components/site/visuals";
import { products } from "@/data/site";

export const Route = createFileRoute("/products/$slug")({
  loader: ({ params }) => { const product=products.find(item=>item.slug===params.slug); if(!product) throw notFound(); return product; },
  head: ({loaderData}) => { const title=loaderData?.name ?? "Product"; const description=loaderData?.description ?? "ARTECHZO technology product."; return {meta:[{title:`${title} — ARTECHZO`},{name:"description",content:description},{property:"og:title",content:`${title} — ARTECHZO`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}; },
  component: ProductDetailPage,
  notFoundComponent: ProductNotFound,
});

function ProductDetailPage(){const product=Route.useLoaderData();return <main><section className="border-b border-border bg-surface-technical py-16 lg:py-24"><div className="site-container"><Link to="/products" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>All products</Link><div className="mt-12 grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div><p className="eyebrow">{product.category}</p><h1 className="mt-5 text-balance text-4xl font-semibold leading-tight sm:text-6xl">{product.name}</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">{product.description}</p><Button asChild className="mt-8"><Link to="/contact">Discuss this product <ArrowRight/></Link></Button></div><ProductVisual product={product}/></div></div></section><section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-2 lg:gap-20"><div><p className="eyebrow">THE PROBLEM</p><h2 className="mt-4 text-3xl font-semibold">A practical challenge worth solving well.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">{product.problem}</p></div><div><p className="eyebrow">INTENDED SOLUTION</p><h2 className="mt-4 text-3xl font-semibold">Focused technology, clearly applied.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">{product.solution}</p></div></div></section><section className="section-space border-y border-border bg-muted/35"><div className="site-container"><p className="eyebrow">SYSTEM VIEW</p><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">How information moves through the product.</h2><div className="mt-10"><ArchitectureFlow steps={product.flow}/></div></div></section><section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-2 lg:gap-20"><div><p className="eyebrow">FUNCTIONAL AREAS</p><div className="mt-6 divide-y divide-border border-y border-border">{product.functionalAreas.map(area=><div key={area} className="flex items-center gap-3 py-4"><Check className="h-4 w-4 text-primary"/><span className="font-medium">{area}</span></div>)}</div></div><div><p className="eyebrow">RELEVANT USE CASES</p><div className="mt-6 divide-y divide-border border-y border-border">{product.useCases.map(area=><div key={area} className="flex items-center gap-3 py-4"><Check className="h-4 w-4 text-primary"/><span className="font-medium">{area}</span></div>)}</div>{product.slug==="ai-data-extraction-engine"&&<p className="mt-6 flex gap-3 bg-accent-soft p-5 text-sm leading-6 text-muted-foreground"><ShieldCheck className="h-5 w-5 shrink-0 text-primary"/>Designed for publicly accessible or otherwise authorized information, with responsible access and respect for website restrictions.</p>}</div></div></section><CtaBand/></main>}

function ProductNotFound(){return <main className="site-container flex min-h-[65vh] flex-col items-center justify-center text-center"><p className="eyebrow">PRODUCT NOT FOUND</p><h1 className="mt-4 text-4xl font-semibold">This product page is unavailable.</h1><Button asChild className="mt-7"><Link to="/products">Browse products</Link></Button></main>}
